name: Build CI

on:
  push:
    branches: 
      - main
      - 'feature/**'
      - 'bugfix/**' 
  workflow_dispatch:

env:  
  OCTOPUS_PROJECT_NAME: Trident
  OCTOPUS_FEATURE_BRANCH_CHANNEL: Default
  OCTOPUS_FEATURE_BRANCH_ENVIRONMENT: Development
  OCTOPUS_RELEASE_CHANNEL: Release
  OCTOPUS_RELEASE_ENVIRONMENT: Staging  
  OCTOPUS_SPACE: Integration-Flyway
  OCTOPUS_API_KEY: ${{ secrets.OCTOPUSSERVERAPIKEY }}
  OCTOPUS_URL: ${{ secrets.OCTOPUSSERVERURL }}

jobs:

  build-and-push-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - id: ReleaseNum
        name: Set Release Number
        run: |
          $locationOfProject = "src/Octopus.Trident.Web/Octopus.Trident.Web.csproj"
          $projectContents = Get-Content $locationOfProject
          $projectAsXML = [xml]$projectContents
          $versionPrefix = $projectAsXML.Project.PropertyGroup.VersionPrefix

          Write-Host "The version prefix is $versionPrefix"

          $branchName = (((${env:GITHUB_REF} -replace "refs/heads/", "") -replace "feature/", "") -replace "bugfix/", "") -replace " ", ""
          Write-Host "The Branch Name is: $branchName"

          $versionNumber = "$($versionPrefix).${env:GITHUB_RUN_NUMBER}"
          Write-Host "The version number is now $versionNumber"

          if ($branchName -ne "main")
          {
              Write-Host "The branch is not the main branch, using the feature branch settings instead."
              
              $versionNumber = "$versionNumber-$branchName"
              Write-Host "The version number is now $versionNumber"
          }          

          Write-Host "Setting the Output Variable VERSION to $versionNumber"
          Write-Output "APP_VERSION=$versionNumber" >> $Env:GITHUB_OUTPUT

        shell: pwsh
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: create artifacts folder
        run: |
          mkdir "$GITHUB_WORKSPACE/artifacts"
          mkdir "$GITHUB_WORKSPACE/artifacts/web"
          mkdir "$GITHUB_WORKSPACE/artifacts/database"          

      - name: restore dependencies for application
        working-directory: src
        run: dotnet restore

      - name: build website           
        working-directory: src/Octopus.Trident.Web
        run: dotnet publish --output "$GITHUB_WORKSPACE/artifacts/web" -c Release --runtime win-x64 --sc false --p:Version=${{ steps.ReleaseNum.outputs.APP_VERSION }}

      - name: build database        
        working-directory: src/Octopus.Trident.Database.DbUp
        run: dotnet publish --output "$GITHUB_WORKSPACE/artifacts/database" -c Release --runtime win-x64 --sc true --p:PublishSingleFile=true --p:PublishTrimmed=true --p:Version=${{ steps.ReleaseNum.outputs.APP_VERSION }}            
          
